package:
  name: texture-atlas
  version: {{ environ['GIT_DESCRIBE_TAG'] ~ "." ~ environ['GIT_DESCRIBE_NUMBER'] ~ "." ~ environ['GIT_DESCRIBE_HASH'] }}

source:
  patches:
    - texture-atlas.patch
  git_tag: v1.0.2
  git_url: git@gitlab.kitware.com:core3d/core3d-keu.git

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - vtk v8.1.1.*    # vtk from kitware-geospatial
    - eigen
    - opencv
    - libgdal 2.2.*
    # otherwise we get an undefined error
    - x264
    - libboost
  run:
    - vtk v8.1.1.*    # vtk from kitware-geospatial
    - eigen
    - opencv
    - libgdal 2.2.*
    # otherwise we get an undefined error
    - x264
    - libboost

test:
  commands:
    - run_texture_mapping
